version: 2
jobs:
    build:
        machine: true
        steps:
        - checkout

        - run:
            name: Build image
            command: docker-compose build

        - run:
            name: Launch containers
            command: docker-compose up -d

        - run:
            name: Waiting to start containers
            command: sleep 10

        - run:
            name: Test Wiki page
            command: |
                curl -v http://localhost:8080/wiki:welcome
                curl -v -X POST -d 'u=root' -d 'p=password' 'http://localhost:8080/doku.php?id=start&do=login&sectok='

        - run:
            name: Remove containers
            command: docker-compose down
    trigger:
        machine: true
        steps:
        - checkout

        - run:
            name: Trigger to DockerHub
            command: >
                curl -v -sS -H "Content-Type: application/json" -X POST
                --data '{"source_type": "Tag", "source_name": "master"}'
                -L https://registry.hub.docker.com/u/mizunashi/dokuwiki/trigger/${TRIGGER_TOKEN}/

        - run:
            name: Tag trigger to DockerHub
            command: >
                curl -v -sS -H "Content-Type: application/json" -X POST
                --data "{\"source_type\": \"Tag\", \"source_name\": \"$(cat Dockerfile | grep DOKUWIKI_VERSION= | sed 's/^.*DOKUWIKI_VERSION="\(.*\)".*$/\1/')\"}"
                -L https://registry.hub.docker.com/u/mizunashi/dokuwiki/trigger/${TRIGGER_TOKEN}/

workflows:
    version: 2
    main:
        jobs:
        - build
        - trigger:
            requires:
            - build
            filters:
                branches:
                    only: master
